version: "2"
services:
    pg_projeto:
        image: projetofinalmaster:v1
        restart: always
        stdin_open: true
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - ./datadb:/data/db
            - ./databkp:/data/backup
    pg_slave:
        image: projetofinalslave:v1
        restart: always
        stdin_open: true
        tty: true
        ports: 
            - "15432:5432"            
        volumes: 
            - ./databkp:/data/backup
            - ./dataslv:/data/db

